function [plotObj] = plotProfiles(uLabSpace, xLabSpace, tLabSpace, plotTime, linesToPlot)
% Function for plotting concentration profiles generated by modl3
% Three first input correspond to modl3 output
% vector plotTime is lab time for which you want to plot
% linesToPlot is a vector for choosing which lines to plot - values 1-4

% Adds sum of gelled and ungelled alginate as z = 4
if ismember(4, linesToPlot)
    uLabSpace(:,:,4) = uLabSpace(:,:,2) + uLabSpace(:,:,3);
end

% Set colors for line of the four species
lineColors = {'red' 'green' 'blue' 'cyan'};


figure;
hold on

for tplot = plotTime
    for line = linesToPlot
        plotObj = plot(xLabSpace, uLabSpace(tplot, :, line),'Color',lineColors{line});
            
            
    end
end

title('Gelling profiles')
ylabel('Concentration [M]')
xlabel('Distance [m]')
    
