function [plotObj] = plotProfiles(uLabSpace, xLabSpace, tLabSpace, plotTime, linesToPlot)
% Function for plotting concentration profiles generated by modl3
% Three first input correspond to modl3 output
% vector plotTime is lab time for which you want to plot
% linesToPlot is a vector for choosing which lines to plot - values 1-4

% Adds sum of gelled and ungelled alginate as z = 4
if ismember(4, linesToPlot)
    uLabSpace(:,:,4) = uLabSpace(:,:,2) + uLabSpace(:,:,3);
end

% Set colors and labels for line of the four species
lineColors = {'red' 'green' 'blue' 'cyan'};
lineLabels = {'Ca^2^+', 'monomer', 'gel', 'total alginate'};

plotObj = [];

figure;
hold on

% Loops through all plot times and all lines to plot
for tplot = plotTime
    for line = linesToPlot
        % Line color and line name is specified
        plotObj = [plotObj plot(xLabSpace, uLabSpace(tplot, :, line),'Color',lineColors{line},'DisplayName',lineLabels{line})];
            
            
    end
end

title('Gelling profiles')
ylabel('Concentration [M]')
xlabel('Distance [m]')
legend(plotObj(1:length(linesToPlot)))

    
